query History {
  history {
    runs {
      id
      runNo
      state
      startedAt
      endedAt
      script
      exception
    }
    traces {
      id
      runNo
      traceId
      startedAt
      endedAt
    }
    prompts {
      id
      runNo
      traceId
      promptNo
      event
      startedAt
      fileName
      lineNo
    }
  }
}
